owner: automatixxx 
repo: muzmon

sites:
  - name: SSO
    url: https://sso.muzeumsusch.ch/-/health/live/
  - name: CLOUD
    url: https://cloud.muzeumsusch.ch/status.php
    expectedResponseContains:
      - '"maintenance":false'
      
status-website:
  cname: monitoring.muzeumsusch.ch
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Muzeum Susch
  introTitle: Main internet services uptime
  introMessage: Visit our website for more information - https://muzeumsusch.ch
  navbar:
    - title: Status
      href: /
  theme: ocean

i18n:
  footer: The Susch Cloud is powered by [IT ZONE](https://it-zone.org)    
  
